// DO NOT EDIT. generated by github.com/tinywasm/ormc

package sitecontent

import (
	"github.com/tinywasm/model"
)

type About struct {
	Title string
	Body string
	Image string
	Mission string
	Vision string
}

func (m *About) ModelName() string { return "about" }

func (m *About) Schema() []model.Field { return AboutModel.Fields }

func (m *About) Pointers() []any { return []any{&m.Title, &m.Body, &m.Image, &m.Mission, &m.Vision} }

func (m *About) IsNil() bool { return m == nil }

func (m *About) EncodeFields(w model.FieldWriter) {
	w.String("Title", m.Title)
	w.String("Body", m.Body)
	w.String("Image", m.Image)
	w.String("Mission", m.Mission)
	w.String("Vision", m.Vision)
}

func (m *About) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("Title"); ok { m.Title = v }
	if v, ok := r.String("Body"); ok { m.Body = v }
	if v, ok := r.String("Image"); ok { m.Image = v }
	if v, ok := r.String("Mission"); ok { m.Mission = v }
	if v, ok := r.String("Vision"); ok { m.Vision = v }
}

type AboutList []*About

func (s *AboutList) Schema() []model.Field { return nil }
func (s *AboutList) Pointers() []any     { return nil }
func (s *AboutList) Len() int             { return len(*s) }
func (s *AboutList) At(i int) model.Fielder { return (*s)[i] }
func (s *AboutList) Append() model.Fielder  { v := &About{}; *s = append(*s, v); return v }
func (s *AboutList) IsNil() bool          { return s == nil }
func (s *AboutList) EncodeFields(_ model.FieldWriter) {}
func (s *AboutList) DecodeFields(_ model.FieldReader) {}

func (m *About) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
