// DO NOT EDIT. generated by github.com/tinywasm/ormc

package sitecontent

import (
	"github.com/tinywasm/model"
)

type Brand struct {
	Name string
	WideLogo string
	CompactLogo string
	LogoAlt string
	PrimaryColor string
}

func (m *Brand) ModelName() string { return "brand" }

func (m *Brand) Schema() []model.Field { return BrandModel.Fields }

func (m *Brand) Pointers() []any { return []any{&m.Name, &m.WideLogo, &m.CompactLogo, &m.LogoAlt, &m.PrimaryColor} }

func (m *Brand) IsNil() bool { return m == nil }

func (m *Brand) EncodeFields(w model.FieldWriter) {
	w.String("Name", m.Name)
	w.String("WideLogo", m.WideLogo)
	w.String("CompactLogo", m.CompactLogo)
	w.String("LogoAlt", m.LogoAlt)
	w.String("PrimaryColor", m.PrimaryColor)
}

func (m *Brand) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("Name"); ok { m.Name = v }
	if v, ok := r.String("WideLogo"); ok { m.WideLogo = v }
	if v, ok := r.String("CompactLogo"); ok { m.CompactLogo = v }
	if v, ok := r.String("LogoAlt"); ok { m.LogoAlt = v }
	if v, ok := r.String("PrimaryColor"); ok { m.PrimaryColor = v }
}

type BrandList []*Brand

func (s *BrandList) Schema() []model.Field { return nil }
func (s *BrandList) Pointers() []any     { return nil }
func (s *BrandList) Len() int             { return len(*s) }
func (s *BrandList) At(i int) model.Fielder { return (*s)[i] }
func (s *BrandList) Append() model.Fielder  { v := &Brand{}; *s = append(*s, v); return v }
func (s *BrandList) IsNil() bool          { return s == nil }
func (s *BrandList) EncodeFields(_ model.FieldWriter) {}
func (s *BrandList) DecodeFields(_ model.FieldReader) {}

func (m *Brand) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
