// DO NOT EDIT. generated by github.com/tinywasm/ormc

package sitecontent

import (
	"github.com/tinywasm/model"
)

type Contact struct {
	Phone string
	Email string
	Address string
}

func (m *Contact) ModelName() string { return "contact" }

func (m *Contact) Schema() []model.Field { return ContactModel.Fields }

func (m *Contact) Pointers() []any { return []any{&m.Phone, &m.Email, &m.Address} }

func (m *Contact) IsNil() bool { return m == nil }

func (m *Contact) EncodeFields(w model.FieldWriter) {
	w.String("Phone", m.Phone)
	w.String("Email", m.Email)
	w.String("Address", m.Address)
}

func (m *Contact) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("Phone"); ok { m.Phone = v }
	if v, ok := r.String("Email"); ok { m.Email = v }
	if v, ok := r.String("Address"); ok { m.Address = v }
}

type ContactList []*Contact

func (s *ContactList) Schema() []model.Field { return nil }
func (s *ContactList) Pointers() []any     { return nil }
func (s *ContactList) Len() int             { return len(*s) }
func (s *ContactList) At(i int) model.Fielder { return (*s)[i] }
func (s *ContactList) Append() model.Fielder  { v := &Contact{}; *s = append(*s, v); return v }
func (s *ContactList) IsNil() bool          { return s == nil }
func (s *ContactList) EncodeFields(_ model.FieldWriter) {}
func (s *ContactList) DecodeFields(_ model.FieldReader) {}

func (m *Contact) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
