// DO NOT EDIT. generated by github.com/tinywasm/ormc

package sitecontent

import (
	"github.com/tinywasm/model"
	"github.com/tinywasm/orm"
)

type Content struct {
	SiteId string
	Brand Brand
	Contact Contact
	Hero Hero
	About About
	Services []Service
	Stats []Stat
	Hours []Schedule
	Map Map
	Seo SEO
	Images []ImageRef
}

func (m *Content) ModelName() string { return "content" }

func (m *Content) Schema() []model.Field { return ContentModel.Fields }

func (m *Content) Pointers() []any { return []any{&m.SiteId, &m.Brand, &m.Contact, &m.Hero, &m.About, &m.Services, &m.Stats, &m.Hours, &m.Map, &m.Seo, &m.Images} }

func (m *Content) IsNil() bool { return m == nil }

func (m *Content) EncodeFields(w model.FieldWriter) {
	w.String("SiteID", m.SiteId)
	w.Object("Brand", &m.Brand)
	w.Object("Contact", &m.Contact)
	w.Object("Hero", &m.Hero)
	w.Object("About", &m.About)
		{
			arr := w.Array("Services", len(m.Services))
			for _, x := range m.Services {
				arr.Object(&x)
			}
			arr.Close()
		}
		{
			arr := w.Array("Stats", len(m.Stats))
			for _, x := range m.Stats {
				arr.Object(&x)
			}
			arr.Close()
		}
		{
			arr := w.Array("Hours", len(m.Hours))
			for _, x := range m.Hours {
				arr.Object(&x)
			}
			arr.Close()
		}
	w.Object("Map", &m.Map)
	w.Object("SEO", &m.Seo)
		{
			arr := w.Array("Images", len(m.Images))
			for _, x := range m.Images {
				arr.Object(&x)
			}
			arr.Close()
		}
}

func (m *Content) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("SiteID"); ok { m.SiteId = v }
	r.Object("Brand", &m.Brand)
	r.Object("Contact", &m.Contact)
	r.Object("Hero", &m.Hero)
	r.Object("About", &m.About)
	if arr, ok := r.Array("Services"); ok {
		n := arr.Len()
		m.Services = make([]Service, n)
		for i := 0; i < n; i++ {
			arr.Object(i, &m.Services[i])
		}
	}
	if arr, ok := r.Array("Stats"); ok {
		n := arr.Len()
		m.Stats = make([]Stat, n)
		for i := 0; i < n; i++ {
			arr.Object(i, &m.Stats[i])
		}
	}
	if arr, ok := r.Array("Hours"); ok {
		n := arr.Len()
		m.Hours = make([]Schedule, n)
		for i := 0; i < n; i++ {
			arr.Object(i, &m.Hours[i])
		}
	}
	r.Object("Map", &m.Map)
	r.Object("SEO", &m.Seo)
	if arr, ok := r.Array("Images"); ok {
		n := arr.Len()
		m.Images = make([]ImageRef, n)
		for i := 0; i < n; i++ {
			arr.Object(i, &m.Images[i])
		}
	}
}

type ContentList []*Content

func (s *ContentList) Schema() []model.Field { return nil }
func (s *ContentList) Pointers() []any     { return nil }
func (s *ContentList) Len() int             { return len(*s) }
func (s *ContentList) At(i int) model.Fielder { return (*s)[i] }
func (s *ContentList) Append() model.Fielder  { v := &Content{}; *s = append(*s, v); return v }
func (s *ContentList) IsNil() bool          { return s == nil }
func (s *ContentList) EncodeFields(_ model.FieldWriter) {}
func (s *ContentList) DecodeFields(_ model.FieldReader) {}

func (m *Content) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Content_ = struct {
	SiteId string
	Brand string
	Contact string
	Hero string
	About string
	Services string
	Stats string
	Hours string
	Map string
	Seo string
	Images string
}{
	SiteId: "SiteID",
	Brand: "Brand",
	Contact: "Contact",
	Hero: "Hero",
	About: "About",
	Services: "Services",
	Stats: "Stats",
	Hours: "Hours",
	Map: "Map",
	Seo: "SEO",
	Images: "Images",
}

func ReadOneContent(qb *orm.QB, model *Content) (*Content, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllContent(qb *orm.QB) (ContentList, error) {
	var results ContentList
	err := orm.ReadAll(qb,
		func() *Content { return &Content{} },
		func(m *Content) { results = append(results, m) },
	)
	return results, err
}
