// DO NOT EDIT. generated by github.com/tinywasm/ormc

package sitecontent

import (
	"github.com/tinywasm/model"
)

type ImageItem struct {
	Key string
}

func (m *ImageItem) ModelName() string { return "image_item" }

func (m *ImageItem) Schema() []model.Field { return ImageItemModel.Fields }

func (m *ImageItem) Pointers() []any { return []any{&m.Key} }

func (m *ImageItem) IsNil() bool { return m == nil }

func (m *ImageItem) EncodeFields(w model.FieldWriter) {
	w.String("Key", m.Key)
}

func (m *ImageItem) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("Key"); ok { m.Key = v }
}

type ImageItemList []*ImageItem

func (s *ImageItemList) Schema() []model.Field { return nil }
func (s *ImageItemList) Pointers() []any     { return nil }
func (s *ImageItemList) Len() int             { return len(*s) }
func (s *ImageItemList) At(i int) model.Fielder { return (*s)[i] }
func (s *ImageItemList) Append() model.Fielder  { v := &ImageItem{}; *s = append(*s, v); return v }
func (s *ImageItemList) IsNil() bool          { return s == nil }
func (s *ImageItemList) EncodeFields(_ model.FieldWriter) {}
func (s *ImageItemList) DecodeFields(_ model.FieldReader) {}

func (m *ImageItem) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type Link struct {
	Text string
	Url string
}

func (m *Link) ModelName() string { return "link" }

func (m *Link) Schema() []model.Field { return LinkModel.Fields }

func (m *Link) Pointers() []any { return []any{&m.Text, &m.Url} }

func (m *Link) IsNil() bool { return m == nil }

func (m *Link) EncodeFields(w model.FieldWriter) {
	w.String("Text", m.Text)
	w.String("URL", m.Url)
}

func (m *Link) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("Text"); ok { m.Text = v }
	if v, ok := r.String("URL"); ok { m.Url = v }
}

type LinkList []*Link

func (s *LinkList) Schema() []model.Field { return nil }
func (s *LinkList) Pointers() []any     { return nil }
func (s *LinkList) Len() int             { return len(*s) }
func (s *LinkList) At(i int) model.Fielder { return (*s)[i] }
func (s *LinkList) Append() model.Fielder  { v := &Link{}; *s = append(*s, v); return v }
func (s *LinkList) IsNil() bool          { return s == nil }
func (s *LinkList) EncodeFields(_ model.FieldWriter) {}
func (s *LinkList) DecodeFields(_ model.FieldReader) {}

func (m *Link) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type Hero struct {
	Title string
	Subtitle string
	CtAs []Link
	Images []ImageItem
}

func (m *Hero) ModelName() string { return "hero" }

func (m *Hero) Schema() []model.Field { return HeroModel.Fields }

func (m *Hero) Pointers() []any { return []any{&m.Title, &m.Subtitle, &m.CtAs, &m.Images} }

func (m *Hero) IsNil() bool { return m == nil }

func (m *Hero) EncodeFields(w model.FieldWriter) {
	w.String("Title", m.Title)
	w.String("Subtitle", m.Subtitle)
		{
			arr := w.Array("CTAs", len(m.CtAs))
			for _, x := range m.CtAs {
				arr.Object(&x)
			}
			arr.Close()
		}
		{
			arr := w.Array("Images", len(m.Images))
			for _, x := range m.Images {
				arr.Object(&x)
			}
			arr.Close()
		}
}

func (m *Hero) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("Title"); ok { m.Title = v }
	if v, ok := r.String("Subtitle"); ok { m.Subtitle = v }
	if arr, ok := r.Array("CTAs"); ok {
		n := arr.Len()
		m.CtAs = make([]Link, n)
		for i := 0; i < n; i++ {
			arr.Object(i, &m.CtAs[i])
		}
	}
	if arr, ok := r.Array("Images"); ok {
		n := arr.Len()
		m.Images = make([]ImageItem, n)
		for i := 0; i < n; i++ {
			arr.Object(i, &m.Images[i])
		}
	}
}

type HeroList []*Hero

func (s *HeroList) Schema() []model.Field { return nil }
func (s *HeroList) Pointers() []any     { return nil }
func (s *HeroList) Len() int             { return len(*s) }
func (s *HeroList) At(i int) model.Fielder { return (*s)[i] }
func (s *HeroList) Append() model.Fielder  { v := &Hero{}; *s = append(*s, v); return v }
func (s *HeroList) IsNil() bool          { return s == nil }
func (s *HeroList) EncodeFields(_ model.FieldWriter) {}
func (s *HeroList) DecodeFields(_ model.FieldReader) {}

func (m *Hero) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
