// DO NOT EDIT. generated by github.com/tinywasm/ormc

package sitecontent

import (
	"github.com/tinywasm/model"
)

type ImageRef struct {
	Key string
	Alt string
	Usage string
}

func (m *ImageRef) ModelName() string { return "image_ref" }

func (m *ImageRef) Schema() []model.Field { return ImageRefModel.Fields }

func (m *ImageRef) Pointers() []any { return []any{&m.Key, &m.Alt, &m.Usage} }

func (m *ImageRef) IsNil() bool { return m == nil }

func (m *ImageRef) EncodeFields(w model.FieldWriter) {
	w.String("Key", m.Key)
	w.String("Alt", m.Alt)
	w.String("Usage", m.Usage)
}

func (m *ImageRef) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("Key"); ok { m.Key = v }
	if v, ok := r.String("Alt"); ok { m.Alt = v }
	if v, ok := r.String("Usage"); ok { m.Usage = v }
}

type ImageRefList []*ImageRef

func (s *ImageRefList) Schema() []model.Field { return nil }
func (s *ImageRefList) Pointers() []any     { return nil }
func (s *ImageRefList) Len() int             { return len(*s) }
func (s *ImageRefList) At(i int) model.Fielder { return (*s)[i] }
func (s *ImageRefList) Append() model.Fielder  { v := &ImageRef{}; *s = append(*s, v); return v }
func (s *ImageRefList) IsNil() bool          { return s == nil }
func (s *ImageRefList) EncodeFields(_ model.FieldWriter) {}
func (s *ImageRefList) DecodeFields(_ model.FieldReader) {}

func (m *ImageRef) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
