// DO NOT EDIT. generated by github.com/tinywasm/ormc

package sitecontent

import (
	"github.com/tinywasm/model"
)

type Schedule struct {
	Days string
	Hours string
}

func (m *Schedule) ModelName() string { return "schedule" }

func (m *Schedule) Schema() []model.Field { return ScheduleModel.Fields }

func (m *Schedule) Pointers() []any { return []any{&m.Days, &m.Hours} }

func (m *Schedule) IsNil() bool { return m == nil }

func (m *Schedule) EncodeFields(w model.FieldWriter) {
	w.String("Days", m.Days)
	w.String("Hours", m.Hours)
}

func (m *Schedule) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("Days"); ok { m.Days = v }
	if v, ok := r.String("Hours"); ok { m.Hours = v }
}

type ScheduleList []*Schedule

func (s *ScheduleList) Schema() []model.Field { return nil }
func (s *ScheduleList) Pointers() []any     { return nil }
func (s *ScheduleList) Len() int             { return len(*s) }
func (s *ScheduleList) At(i int) model.Fielder { return (*s)[i] }
func (s *ScheduleList) Append() model.Fielder  { v := &Schedule{}; *s = append(*s, v); return v }
func (s *ScheduleList) IsNil() bool          { return s == nil }
func (s *ScheduleList) EncodeFields(_ model.FieldWriter) {}
func (s *ScheduleList) DecodeFields(_ model.FieldReader) {}

func (m *Schedule) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
