// DO NOT EDIT. generated by github.com/tinywasm/ormc

package sitecontent

import (
	"github.com/tinywasm/model"
)

type SEO struct {
	Description string
	SocialImage string
	SchemaType string
}

func (m *SEO) ModelName() string { return "seo" }

func (m *SEO) Schema() []model.Field { return SEOModel.Fields }

func (m *SEO) Pointers() []any { return []any{&m.Description, &m.SocialImage, &m.SchemaType} }

func (m *SEO) IsNil() bool { return m == nil }

func (m *SEO) EncodeFields(w model.FieldWriter) {
	w.String("Description", m.Description)
	w.String("SocialImage", m.SocialImage)
	w.String("SchemaType", m.SchemaType)
}

func (m *SEO) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("Description"); ok { m.Description = v }
	if v, ok := r.String("SocialImage"); ok { m.SocialImage = v }
	if v, ok := r.String("SchemaType"); ok { m.SchemaType = v }
}

type SEOList []*SEO

func (s *SEOList) Schema() []model.Field { return nil }
func (s *SEOList) Pointers() []any     { return nil }
func (s *SEOList) Len() int             { return len(*s) }
func (s *SEOList) At(i int) model.Fielder { return (*s)[i] }
func (s *SEOList) Append() model.Fielder  { v := &SEO{}; *s = append(*s, v); return v }
func (s *SEOList) IsNil() bool          { return s == nil }
func (s *SEOList) EncodeFields(_ model.FieldWriter) {}
func (s *SEOList) DecodeFields(_ model.FieldReader) {}

func (m *SEO) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
