// DO NOT EDIT. generated by github.com/tinywasm/ormc

package sitecontent

import (
	"github.com/tinywasm/model"
)

type Service struct {
	Slug string
	Title string
	Description string
	Image string
	Body string
}

func (m *Service) ModelName() string { return "service" }

func (m *Service) Schema() []model.Field { return ServiceModel.Fields }

func (m *Service) Pointers() []any { return []any{&m.Slug, &m.Title, &m.Description, &m.Image, &m.Body} }

func (m *Service) IsNil() bool { return m == nil }

func (m *Service) EncodeFields(w model.FieldWriter) {
	w.String("Slug", m.Slug)
	w.String("Title", m.Title)
	w.String("Description", m.Description)
	w.String("Image", m.Image)
	w.String("Body", m.Body)
}

func (m *Service) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("Slug"); ok { m.Slug = v }
	if v, ok := r.String("Title"); ok { m.Title = v }
	if v, ok := r.String("Description"); ok { m.Description = v }
	if v, ok := r.String("Image"); ok { m.Image = v }
	if v, ok := r.String("Body"); ok { m.Body = v }
}

type ServiceList []*Service

func (s *ServiceList) Schema() []model.Field { return nil }
func (s *ServiceList) Pointers() []any     { return nil }
func (s *ServiceList) Len() int             { return len(*s) }
func (s *ServiceList) At(i int) model.Fielder { return (*s)[i] }
func (s *ServiceList) Append() model.Fielder  { v := &Service{}; *s = append(*s, v); return v }
func (s *ServiceList) IsNil() bool          { return s == nil }
func (s *ServiceList) EncodeFields(_ model.FieldWriter) {}
func (s *ServiceList) DecodeFields(_ model.FieldReader) {}

func (m *Service) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
