// DO NOT EDIT. generated by github.com/tinywasm/ormc

package sitecontent

import (
	"github.com/tinywasm/model"
)

type Map struct {
	EmbedUrl string
}

func (m *Map) ModelName() string { return "map" }

func (m *Map) Schema() []model.Field { return MapModel.Fields }

func (m *Map) Pointers() []any { return []any{&m.EmbedUrl} }

func (m *Map) IsNil() bool { return m == nil }

func (m *Map) EncodeFields(w model.FieldWriter) {
	w.String("EmbedURL", m.EmbedUrl)
}

func (m *Map) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("EmbedURL"); ok { m.EmbedUrl = v }
}

type MapList []*Map

func (s *MapList) Schema() []model.Field { return nil }
func (s *MapList) Pointers() []any     { return nil }
func (s *MapList) Len() int             { return len(*s) }
func (s *MapList) At(i int) model.Fielder { return (*s)[i] }
func (s *MapList) Append() model.Fielder  { v := &Map{}; *s = append(*s, v); return v }
func (s *MapList) IsNil() bool          { return s == nil }
func (s *MapList) EncodeFields(_ model.FieldWriter) {}
func (s *MapList) DecodeFields(_ model.FieldReader) {}

func (m *Map) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
