// DO NOT EDIT. generated by github.com/tinywasm/ormc

package sitecontent

import (
	"github.com/tinywasm/model"
)

type Stat struct {
	Value string
	Label string
}

func (m *Stat) ModelName() string { return "stat" }

func (m *Stat) Schema() []model.Field { return StatModel.Fields }

func (m *Stat) Pointers() []any { return []any{&m.Value, &m.Label} }

func (m *Stat) IsNil() bool { return m == nil }

func (m *Stat) EncodeFields(w model.FieldWriter) {
	w.String("Value", m.Value)
	w.String("Label", m.Label)
}

func (m *Stat) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("Value"); ok { m.Value = v }
	if v, ok := r.String("Label"); ok { m.Label = v }
}

type StatList []*Stat

func (s *StatList) Schema() []model.Field { return nil }
func (s *StatList) Pointers() []any     { return nil }
func (s *StatList) Len() int             { return len(*s) }
func (s *StatList) At(i int) model.Fielder { return (*s)[i] }
func (s *StatList) Append() model.Fielder  { v := &Stat{}; *s = append(*s, v); return v }
func (s *StatList) IsNil() bool          { return s == nil }
func (s *StatList) EncodeFields(_ model.FieldWriter) {}
func (s *StatList) DecodeFields(_ model.FieldReader) {}

func (m *Stat) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
